//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banhuitong.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Banhuitong.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap AddImg {
            get {
                object obj = ResourceManager.GetObject("AddImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon App72 {
            get {
                object obj = ResourceManager.GetObject("App72", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 …… 的本地化字符串。
        /// </summary>
        internal static string Commons_Ellipse {
            get {
                return ResourceManager.GetString("Commons_Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        internal static string Commons_Female {
            get {
                return ResourceManager.GetString("Commons_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        internal static string Commons_Male {
            get {
                return ResourceManager.GetString("Commons_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string Commons_No {
            get {
                return ResourceManager.GetString("Commons_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ， 的本地化字符串。
        /// </summary>
        internal static string Commons_Separator {
            get {
                return ResourceManager.GetString("Commons_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Commons_Unknown {
            get {
                return ResourceManager.GetString("Commons_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Commons_Yes {
            get {
                return ResourceManager.GetString("Commons_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string ConfirmBox_Caption {
            get {
                return ResourceManager.GetString("ConfirmBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DeleteImg {
            get {
                object obj = ResourceManager.GetObject("DeleteImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 下载完毕 {0} 的本地化字符串。
        /// </summary>
        internal static string DownloadFileDlg_Downloaded {
            get {
                return ResourceManager.GetString("DownloadFileDlg_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载 {0}... 的本地化字符串。
        /// </summary>
        internal static string DownloadFileDlg_Downloading {
            get {
                return ResourceManager.GetString("DownloadFileDlg_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EditImg {
            get {
                object obj = ResourceManager.GetObject("EditImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ErrorBox_Caption {
            get {
                return ResourceManager.GetString("ErrorBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ErrorImg {
            get {
                object obj = ResourceManager.GetObject("ErrorImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 导出Excel 的本地化字符串。
        /// </summary>
        internal static string Excel_SaveFile {
            get {
                return ResourceManager.GetString("Excel_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel文件 (*.xls;*.xlsx)|*.xls;*.xlsx|全部文件 (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string Excel_SaveFile_Filter {
            get {
                return ResourceManager.GetString("Excel_SaveFile_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExcelImg {
            get {
                object obj = ResourceManager.GetObject("ExcelImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ExportImg {
            get {
                object obj = ResourceManager.GetObject("ExportImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Flag1Img {
            get {
                object obj = ResourceManager.GetObject("Flag1Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Flag2Img {
            get {
                object obj = ResourceManager.GetObject("Flag2Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Flag3Img {
            get {
                object obj = ResourceManager.GetObject("Flag3Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Flag4Img {
            get {
                object obj = ResourceManager.GetObject("Flag4Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Flag5Img {
            get {
                object obj = ResourceManager.GetObject("Flag5Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Flag6Img {
            get {
                object obj = ResourceManager.GetObject("Flag6Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        internal static string HttpStatus_Ready {
            get {
                return ResourceManager.GetString("HttpStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在接收数据... 的本地化字符串。
        /// </summary>
        internal static string HttpStatus_Receiving {
            get {
                return ResourceManager.GetString("HttpStatus_Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在发送数据... 的本地化字符串。
        /// </summary>
        internal static string HttpStatus_Sending {
            get {
                return ResourceManager.GetString("HttpStatus_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在等待响应... 的本地化字符串。
        /// </summary>
        internal static string HttpStatus_Waiting {
            get {
                return ResourceManager.GetString("HttpStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string InfoBox_Caption {
            get {
                return ResourceManager.GetString("InfoBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        internal static string InputBox_Caption {
            get {
                return ResourceManager.GetString("InputBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （全部） 的本地化字符串。
        /// </summary>
        internal static string ListControl_ItemAll {
            get {
                return ResourceManager.GetString("ListControl_ItemAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （无） 的本地化字符串。
        /// </summary>
        internal static string ListControl_ItemNone {
            get {
                return ResourceManager.GetString("ListControl_ItemNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LockImg {
            get {
                object obj = ResourceManager.GetObject("LockImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap OkImg {
            get {
                object obj = ResourceManager.GetObject("OkImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PdfImg {
            get {
                object obj = ResourceManager.GetObject("PdfImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ResetImg {
            get {
                object obj = ResourceManager.GetObject("ResetImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 期望返回结果的类型：{0} 
        ///实际返回结果是：{1} 的本地化字符串。
        /// </summary>
        internal static string ResultFormatException_Default {
            get {
                return ResourceManager.GetString("ResultFormatException_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 502错误,服务地址:{0} 的本地化字符串。
        /// </summary>
        internal static string RpcException_BadGateway {
            get {
                return ResourceManager.GetString("RpcException_BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器错误。
        ///请求地址：{0}
        ///响应状态：{1} 的本地化字符串。
        /// </summary>
        internal static string RpcException_Default {
            get {
                return ResourceManager.GetString("RpcException_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止访问此功能，可能登录超时或者未分配足够的权限。
        ///请求地址：{0} 的本地化字符串。
        /// </summary>
        internal static string RpcException_Forbidden {
            get {
                return ResourceManager.GetString("RpcException_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到服务。
        ///请求地址：{0} 的本地化字符串。
        /// </summary>
        internal static string RpcException_NotFound {
            get {
                return ResourceManager.GetString("RpcException_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SearchImg {
            get {
                object obj = ResourceManager.GetObject("SearchImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败！ 的本地化字符串。
        /// </summary>
        internal static string SignIn_Failed {
            get {
                return ResourceManager.GetString("SignIn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StatisticImg {
            get {
                object obj = ResourceManager.GetObject("StatisticImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户：{0} 的本地化字符串。
        /// </summary>
        internal static string StatusBar_CurrentUser {
            get {
                return ResourceManager.GetString("StatusBar_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 {0} 条记录 的本地化字符串。
        /// </summary>
        internal static string StatusBar_TotalRecords {
            get {
                return ResourceManager.GetString("StatusBar_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StopImg {
            get {
                object obj = ResourceManager.GetObject("StopImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 取消(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string StrongConfirmBox_Cancel {
            get {
                return ResourceManager.GetString("StrongConfirmBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续确认 的本地化字符串。
        /// </summary>
        internal static string StrongConfirmBox_Caption {
            get {
                return ResourceManager.GetString("StrongConfirmBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string StrongConfirmBox_OK {
            get {
                return ResourceManager.GetString("StrongConfirmBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入文本“{0}”继续确认 的本地化字符串。
        /// </summary>
        internal static string StrongConfirmBox_Promopt {
            get {
                return ResourceManager.GetString("StrongConfirmBox_Promopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string WarnBox_Caption {
            get {
                return ResourceManager.GetString("WarnBox_Caption", resourceCulture);
            }
        }
    }
}
