//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banhuitong.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Banhuitong.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddImg {
            get {
                object obj = ResourceManager.GetObject("AddImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon App72 {
            get {
                object obj = ResourceManager.GetObject("App72", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …….
        /// </summary>
        internal static string Commons_Ellipse {
            get {
                return ResourceManager.GetString("Commons_Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        internal static string Commons_Female {
            get {
                return ResourceManager.GetString("Commons_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        internal static string Commons_Male {
            get {
                return ResourceManager.GetString("Commons_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        internal static string Commons_No {
            get {
                return ResourceManager.GetString("Commons_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ，.
        /// </summary>
        internal static string Commons_Separator {
            get {
                return ResourceManager.GetString("Commons_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        internal static string Commons_Unknown {
            get {
                return ResourceManager.GetString("Commons_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        internal static string Commons_Yes {
            get {
                return ResourceManager.GetString("Commons_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string ConfirmBox_Caption {
            get {
                return ResourceManager.GetString("ConfirmBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteImg {
            get {
                object obj = ResourceManager.GetObject("DeleteImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完毕 {0}.
        /// </summary>
        internal static string DownloadFileDlg_Downloaded {
            get {
                return ResourceManager.GetString("DownloadFileDlg_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载 {0}....
        /// </summary>
        internal static string DownloadFileDlg_Downloading {
            get {
                return ResourceManager.GetString("DownloadFileDlg_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditImg {
            get {
                object obj = ResourceManager.GetObject("EditImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string ErrorBox_Caption {
            get {
                return ResourceManager.GetString("ErrorBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorImg {
            get {
                object obj = ResourceManager.GetObject("ErrorImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出Excel.
        /// </summary>
        internal static string Excel_SaveFile {
            get {
                return ResourceManager.GetString("Excel_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel文件 (*.xls;*.xlsx)|*.xls;*.xlsx|全部文件 (*.*)|*.*.
        /// </summary>
        internal static string Excel_SaveFile_Filter {
            get {
                return ResourceManager.GetString("Excel_SaveFile_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelImg {
            get {
                object obj = ResourceManager.GetObject("ExcelImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportImg {
            get {
                object obj = ResourceManager.GetObject("ExportImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag1Img {
            get {
                object obj = ResourceManager.GetObject("Flag1Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag2Img {
            get {
                object obj = ResourceManager.GetObject("Flag2Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag3Img {
            get {
                object obj = ResourceManager.GetObject("Flag3Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag4Img {
            get {
                object obj = ResourceManager.GetObject("Flag4Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag5Img {
            get {
                object obj = ResourceManager.GetObject("Flag5Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag6Img {
            get {
                object obj = ResourceManager.GetObject("Flag6Img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 就绪.
        /// </summary>
        internal static string HttpStatus_Ready {
            get {
                return ResourceManager.GetString("HttpStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在接收数据....
        /// </summary>
        internal static string HttpStatus_Receiving {
            get {
                return ResourceManager.GetString("HttpStatus_Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在发送数据....
        /// </summary>
        internal static string HttpStatus_Sending {
            get {
                return ResourceManager.GetString("HttpStatus_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在等待响应....
        /// </summary>
        internal static string HttpStatus_Waiting {
            get {
                return ResourceManager.GetString("HttpStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息.
        /// </summary>
        internal static string InfoBox_Caption {
            get {
                return ResourceManager.GetString("InfoBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入.
        /// </summary>
        internal static string InputBox_Caption {
            get {
                return ResourceManager.GetString("InputBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （全部）.
        /// </summary>
        internal static string ListControl_ItemAll {
            get {
                return ResourceManager.GetString("ListControl_ItemAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （无）.
        /// </summary>
        internal static string ListControl_ItemNone {
            get {
                return ResourceManager.GetString("ListControl_ItemNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockImg {
            get {
                object obj = ResourceManager.GetObject("LockImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OkImg {
            get {
                object obj = ResourceManager.GetObject("OkImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PdfImg {
            get {
                object obj = ResourceManager.GetObject("PdfImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResetImg {
            get {
                object obj = ResourceManager.GetObject("ResetImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期望返回结果的类型：{0} 
        ///实际返回结果是：{1}.
        /// </summary>
        internal static string ResultFormatException_Default {
            get {
                return ResourceManager.GetString("ResultFormatException_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器错误。
        ///请求地址：{0}
        ///响应状态：{1}.
        /// </summary>
        internal static string RpcException_Default {
            get {
                return ResourceManager.GetString("RpcException_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁止访问此功能，可能登录超时或者未分配足够的权限。
        ///请求地址：{0}.
        /// </summary>
        internal static string RpcException_Forbidden {
            get {
                return ResourceManager.GetString("RpcException_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到服务。
        ///请求地址：{0}.
        /// </summary>
        internal static string RpcException_NotFound {
            get {
                return ResourceManager.GetString("RpcException_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchImg {
            get {
                object obj = ResourceManager.GetObject("SearchImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录失败！.
        /// </summary>
        internal static string SignIn_Failed {
            get {
                return ResourceManager.GetString("SignIn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatisticImg {
            get {
                object obj = ResourceManager.GetObject("StatisticImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前用户：{0}.
        /// </summary>
        internal static string StatusBar_CurrentUser {
            get {
                return ResourceManager.GetString("StatusBar_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共 {0} 条记录.
        /// </summary>
        internal static string StatusBar_TotalRecords {
            get {
                return ResourceManager.GetString("StatusBar_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StopImg {
            get {
                object obj = ResourceManager.GetObject("StopImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消(&amp;C).
        /// </summary>
        internal static string StrongConfirmBox_Cancel {
            get {
                return ResourceManager.GetString("StrongConfirmBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 继续确认.
        /// </summary>
        internal static string StrongConfirmBox_Caption {
            get {
                return ResourceManager.GetString("StrongConfirmBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认(&amp;O).
        /// </summary>
        internal static string StrongConfirmBox_OK {
            get {
                return ResourceManager.GetString("StrongConfirmBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入文本“{0}”继续确认.
        /// </summary>
        internal static string StrongConfirmBox_Promopt {
            get {
                return ResourceManager.GetString("StrongConfirmBox_Promopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string WarnBox_Caption {
            get {
                return ResourceManager.GetString("WarnBox_Caption", resourceCulture);
            }
        }
    }
}
